"""Static Vedic astrology reference data — 9 Grahas and 27 Nakshatras."""

GRAHAS = [
    {
        "id": "surya",
        "name": "Surya",
        "english": "Sun",
        "symbol": "☉",
        "sanskrit": "सूर्य",
        "element": "Fire",
        "gender": "Male",
        "deity": "Surya Dev",
        "day": "Sunday",
        "gemstone": "Ruby",
        "color": "Deep Orange",
        "rules": "Leo",
        "exalted": "Aries",
        "debilitated": "Libra",
        "description": "The luminous soul of the cosmos. Surya governs vitality, authority, self-expression, fatherhood, and the eternal self (Atman). He is the king of the planets, bestowing willpower, leadership, and radiance upon those he favours.",
        "qualities": ["Authority", "Vitality", "Ego", "Leadership", "Willpower", "Clarity"],
    },
    {
        "id": "chandra",
        "name": "Chandra",
        "english": "Moon",
        "symbol": "☾",
        "sanskrit": "चन्द्र",
        "element": "Water",
        "gender": "Female",
        "deity": "Chandra Dev",
        "day": "Monday",
        "gemstone": "Pearl",
        "color": "White / Silver",
        "rules": "Cancer",
        "exalted": "Taurus",
        "debilitated": "Scorpio",
        "description": "The queen of the mind. Chandra rules emotion, intuition, motherhood, memory, and the subconscious. Her waxing and waning mirror the tides of human feeling, making her the most personal of all grahas.",
        "qualities": ["Emotion", "Intuition", "Nurture", "Imagination", "Memory", "Receptivity"],
    },
    {
        "id": "mangala",
        "name": "Mangala",
        "english": "Mars",
        "symbol": "♂",
        "sanskrit": "मङ्गल",
        "element": "Fire",
        "gender": "Male",
        "deity": "Kartikeya",
        "day": "Tuesday",
        "gemstone": "Red Coral",
        "color": "Red",
        "rules": "Aries, Scorpio",
        "exalted": "Capricorn",
        "debilitated": "Cancer",
        "description": "The celestial warrior. Mangala grants courage, discipline, drive, and physical stamina. He governs siblings, property, and the martial arts — a divine commander whose fire must be tempered with wisdom.",
        "qualities": ["Courage", "Action", "Discipline", "Strength", "Passion", "Conflict"],
    },
    {
        "id": "budha",
        "name": "Budha",
        "english": "Mercury",
        "symbol": "☿",
        "sanskrit": "बुध",
        "element": "Earth",
        "gender": "Neutral",
        "deity": "Vishnu",
        "day": "Wednesday",
        "gemstone": "Emerald",
        "color": "Green",
        "rules": "Gemini, Virgo",
        "exalted": "Virgo",
        "debilitated": "Pisces",
        "description": "The prince of intellect. Budha rules speech, logic, commerce, writing, and communication. He is the swift messenger — sharp-witted, analytical, and perpetually youthful.",
        "qualities": ["Intellect", "Speech", "Wit", "Analysis", "Commerce", "Adaptability"],
    },
    {
        "id": "guru",
        "name": "Guru",
        "english": "Jupiter",
        "symbol": "♃",
        "sanskrit": "गुरु",
        "element": "Ether",
        "gender": "Male",
        "deity": "Brihaspati",
        "day": "Thursday",
        "gemstone": "Yellow Sapphire",
        "color": "Yellow / Gold",
        "rules": "Sagittarius, Pisces",
        "exalted": "Cancer",
        "debilitated": "Capricorn",
        "description": "The great benefic, teacher of the gods. Guru brings wisdom, dharma, wealth, children, and spiritual expansion. His grace lifts the soul and opens doors to higher knowledge.",
        "qualities": ["Wisdom", "Expansion", "Dharma", "Optimism", "Philosophy", "Generosity"],
    },
    {
        "id": "shukra",
        "name": "Shukra",
        "english": "Venus",
        "symbol": "♀",
        "sanskrit": "शुक्र",
        "element": "Water",
        "gender": "Female",
        "deity": "Shukracharya",
        "day": "Friday",
        "gemstone": "Diamond",
        "color": "White / Pastel Rainbow",
        "rules": "Taurus, Libra",
        "exalted": "Pisces",
        "debilitated": "Virgo",
        "description": "The goddess of beauty and love. Shukra governs romance, art, luxury, refinement, and all sensual pleasures. She is the muse — teaching the soul to delight in form.",
        "qualities": ["Love", "Beauty", "Art", "Luxury", "Refinement", "Harmony"],
    },
    {
        "id": "shani",
        "name": "Shani",
        "english": "Saturn",
        "symbol": "♄",
        "sanskrit": "शनि",
        "element": "Air",
        "gender": "Neutral",
        "deity": "Shani Dev",
        "day": "Saturday",
        "gemstone": "Blue Sapphire",
        "color": "Deep Blue / Black",
        "rules": "Capricorn, Aquarius",
        "exalted": "Libra",
        "debilitated": "Aries",
        "description": "The stern judge of karma. Shani delivers delayed rewards, life lessons, discipline, and longevity. Though feared, he is the greatest teacher — separating the worthy from the frivolous.",
        "qualities": ["Discipline", "Karma", "Patience", "Longevity", "Restriction", "Mastery"],
    },
    {
        "id": "rahu",
        "name": "Rahu",
        "english": "North Lunar Node",
        "symbol": "☊",
        "sanskrit": "राहु",
        "element": "Air",
        "gender": "Male",
        "deity": "Durga",
        "day": "—",
        "gemstone": "Hessonite (Gomed)",
        "color": "Smoky Grey",
        "rules": "No sign (co-rules Aquarius)",
        "exalted": "Taurus",
        "debilitated": "Scorpio",
        "description": "The shadow of obsession. Rahu is the severed head that devours — amplifying desire, innovation, foreignness, and sudden ascent. He blinds and liberates in equal measure.",
        "qualities": ["Obsession", "Innovation", "Ambition", "Illusion", "Foreign", "Sudden Gain"],
    },
    {
        "id": "ketu",
        "name": "Ketu",
        "english": "South Lunar Node",
        "symbol": "☋",
        "sanskrit": "केतु",
        "element": "Fire",
        "gender": "Male",
        "deity": "Ganesha",
        "day": "—",
        "gemstone": "Cat's Eye (Lehsunia)",
        "color": "Smoky",
        "rules": "No sign (co-rules Scorpio)",
        "exalted": "Scorpio",
        "debilitated": "Taurus",
        "description": "The headless liberator. Ketu severs attachment, grants moksha, mystical intuition, and past-life wisdom. He represents what the soul already knows and must release.",
        "qualities": ["Detachment", "Moksha", "Intuition", "Mysticism", "Past Lives", "Solitude"],
    },
]

NAKSHATRAS = [
    {"id": 1, "name": "Ashwini", "sanskrit": "अश्विनी", "deity": "Ashwini Kumaras", "symbol": "Horse's Head", "ruler": "Ketu", "range": "Aries 0°–13°20′", "gana": "Deva", "quality": "Swift, healing, pioneering", "description": "The horsemen of dawn. Ashwini natives are quick, adventurous healers and initiators who thrive on new beginnings."},
    {"id": 2, "name": "Bharani", "sanskrit": "भरणी", "deity": "Yama", "symbol": "Yoni", "ruler": "Venus", "range": "Aries 13°20′–26°40′", "gana": "Manushya", "quality": "Transformative, sensual, intense", "description": "The bearer. Bharani governs birth, death, and creative transformation — intense, passionate, artistic."},
    {"id": 3, "name": "Krittika", "sanskrit": "कृत्तिका", "deity": "Agni", "symbol": "Razor / Flame", "ruler": "Sun", "range": "Aries 26°40′–Taurus 10°", "gana": "Rakshasa", "quality": "Cutting, purifying, sharp", "description": "The flame-cutter. Krittika burns away impurity with fierce discernment and nurturing heat."},
    {"id": 4, "name": "Rohini", "sanskrit": "रोहिणी", "deity": "Brahma", "symbol": "Chariot / Cow", "ruler": "Moon", "range": "Taurus 10°–23°20′", "gana": "Manushya", "quality": "Fertile, magnetic, artistic", "description": "The red one. Rohini is the most sensual and fertile nakshatra — beloved of the Moon, abundant in beauty and creation."},
    {"id": 5, "name": "Mrigashira", "sanskrit": "मृगशिरा", "deity": "Soma", "symbol": "Deer's Head", "ruler": "Mars", "range": "Taurus 23°20′–Gemini 6°40′", "gana": "Deva", "quality": "Searching, gentle, curious", "description": "The deer's head. Eternal seekers of knowledge and novelty, gentle yet restless wanderers."},
    {"id": 6, "name": "Ardra", "sanskrit": "आर्द्रा", "deity": "Rudra", "symbol": "Teardrop", "ruler": "Rahu", "range": "Gemini 6°40′–20°", "gana": "Manushya", "quality": "Stormy, cleansing, emotional", "description": "The storm of Rudra. Ardra destroys to renew — raw, emotional, a catalyst for deep change."},
    {"id": 7, "name": "Punarvasu", "sanskrit": "पुनर्वसु", "deity": "Aditi", "symbol": "Quiver of Arrows", "ruler": "Jupiter", "range": "Gemini 20°–Cancer 3°20′", "gana": "Deva", "quality": "Renewing, nurturing, philosophical", "description": "The return of the light. Punarvasu natives restore, nurture, and teach with boundless optimism."},
    {"id": 8, "name": "Pushya", "sanskrit": "पुष्य", "deity": "Brihaspati", "symbol": "Lotus / Udder", "ruler": "Saturn", "range": "Cancer 3°20′–16°40′", "gana": "Deva", "quality": "Nourishing, auspicious, protective", "description": "The nourisher. Pushya is the most auspicious nakshatra — nurturing, spiritual, and deeply protective."},
    {"id": 9, "name": "Ashlesha", "sanskrit": "आश्लेषा", "deity": "Nagas", "symbol": "Coiled Serpent", "ruler": "Mercury", "range": "Cancer 16°40′–30°", "gana": "Rakshasa", "quality": "Hypnotic, penetrating, occult", "description": "The embrace of the serpent. Ashlesha grants mystical insight, magnetism, and penetrating psychological depth."},
    {"id": 10, "name": "Magha", "sanskrit": "मघा", "deity": "Pitris (Ancestors)", "symbol": "Throne", "ruler": "Ketu", "range": "Leo 0°–13°20′", "gana": "Rakshasa", "quality": "Regal, ancestral, noble", "description": "The mighty one. Magha bestows ancestral power, regal bearing, and reverence for tradition."},
    {"id": 11, "name": "Purva Phalguni", "sanskrit": "पूर्वफल्गुनी", "deity": "Bhaga", "symbol": "Hammock / Bed", "ruler": "Venus", "range": "Leo 13°20′–26°40′", "gana": "Manushya", "quality": "Playful, luxurious, creative", "description": "The former red one. Celebrates love, leisure, and creative play — the artist at rest."},
    {"id": 12, "name": "Uttara Phalguni", "sanskrit": "उत्तरफल्गुनी", "deity": "Aryaman", "symbol": "Bed / Fig Tree", "ruler": "Sun", "range": "Leo 26°40′–Virgo 10°", "gana": "Manushya", "quality": "Dependable, generous, contractual", "description": "The latter red one. Patron of marriage, partnerships, and generous friendship."},
    {"id": 13, "name": "Hasta", "sanskrit": "हस्त", "deity": "Savitar", "symbol": "Hand", "ruler": "Moon", "range": "Virgo 10°–23°20′", "gana": "Deva", "quality": "Skilful, witty, crafting", "description": "The hand. Hasta grants craftsmanship, cleverness, and the power to manifest through skilled action."},
    {"id": 14, "name": "Chitra", "sanskrit": "चित्रा", "deity": "Tvashtar", "symbol": "Bright Jewel", "ruler": "Mars", "range": "Virgo 23°20′–Libra 6°40′", "gana": "Rakshasa", "quality": "Dazzling, artistic, illusory", "description": "The brilliant. Chitra dazzles with beauty, architectural genius, and magnetic charisma."},
    {"id": 15, "name": "Swati", "sanskrit": "स्वाती", "deity": "Vayu", "symbol": "Young Shoot in Wind", "ruler": "Rahu", "range": "Libra 6°40′–20°", "gana": "Deva", "quality": "Independent, flexible, diplomatic", "description": "The self-going. Swati values independence, diplomacy, and graceful adaptation to the winds of change."},
    {"id": 16, "name": "Vishakha", "sanskrit": "विशाखा", "deity": "Indra-Agni", "symbol": "Triumphal Arch", "ruler": "Jupiter", "range": "Libra 20°–Scorpio 3°20′", "gana": "Rakshasa", "quality": "Goal-driven, focused, ambitious", "description": "The forked branch. Vishakha pursues lofty goals with laser focus and unyielding determination."},
    {"id": 17, "name": "Anuradha", "sanskrit": "अनुराधा", "deity": "Mitra", "symbol": "Lotus", "ruler": "Saturn", "range": "Scorpio 3°20′–16°40′", "gana": "Deva", "quality": "Devoted, friendly, organising", "description": "The disciple of the divine spark. Anuradha excels in friendship, loyalty, and devotional discipline."},
    {"id": 18, "name": "Jyeshtha", "sanskrit": "ज्येष्ठा", "deity": "Indra", "symbol": "Umbrella / Earring", "ruler": "Mercury", "range": "Scorpio 16°40′–30°", "gana": "Rakshasa", "quality": "Eldest, responsible, secretive", "description": "The eldest. Jyeshtha bears great responsibility, hidden power, and protective authority."},
    {"id": 19, "name": "Mula", "sanskrit": "मूल", "deity": "Nirriti", "symbol": "Bunch of Roots", "ruler": "Ketu", "range": "Sagittarius 0°–13°20′", "gana": "Rakshasa", "quality": "Root-seeking, philosophical, radical", "description": "The root. Mula investigates origins with a fearless, truth-seeking, sometimes destructive zeal."},
    {"id": 20, "name": "Purva Ashadha", "sanskrit": "पूर्वाषाढा", "deity": "Apas", "symbol": "Fan / Winnowing Basket", "ruler": "Venus", "range": "Sagittarius 13°20′–26°40′", "gana": "Manushya", "quality": "Invincible, purifying, optimistic", "description": "The undefeated former. Purva Ashadha is early victory — confident, cleansing, philosophical."},
    {"id": 21, "name": "Uttara Ashadha", "sanskrit": "उत्तराषाढा", "deity": "Vishvadevas", "symbol": "Elephant's Tusk", "ruler": "Sun", "range": "Sagittarius 26°40′–Capricorn 10°", "gana": "Manushya", "quality": "Enduring, virtuous, leading", "description": "The undefeated latter. Uttara Ashadha crowns lasting victories through integrity and steady leadership."},
    {"id": 22, "name": "Shravana", "sanskrit": "श्रवण", "deity": "Vishnu", "symbol": "Ear / Three Footsteps", "ruler": "Moon", "range": "Capricorn 10°–23°20′", "gana": "Deva", "quality": "Listening, learned, traditional", "description": "The ear. Shravana listens deeply to sacred knowledge, tradition, and the music of the spheres."},
    {"id": 23, "name": "Dhanishta", "sanskrit": "धनिष्ठा", "deity": "Eight Vasus", "symbol": "Drum", "ruler": "Mars", "range": "Capricorn 23°20′–Aquarius 6°40′", "gana": "Rakshasa", "quality": "Rhythmic, abundant, musical", "description": "The wealthiest. Dhanishta beats the cosmic drum of prosperity, performance, and generous achievement."},
    {"id": 24, "name": "Shatabhisha", "sanskrit": "शतभिषा", "deity": "Varuna", "symbol": "Empty Circle", "ruler": "Rahu", "range": "Aquarius 6°40′–20°", "gana": "Rakshasa", "quality": "Healing, mystical, reclusive", "description": "The hundred healers. Shatabhisha probes the hidden, heals in secret, and guards cosmic law."},
    {"id": 25, "name": "Purva Bhadrapada", "sanskrit": "पूर्वभाद्रपदा", "deity": "Aja Ekapada", "symbol": "Front of Funeral Cot", "ruler": "Jupiter", "range": "Aquarius 20°–Pisces 3°20′", "gana": "Manushya", "quality": "Intense, ascetic, transforming", "description": "The former blessed foot. Purva Bhadrapada burns with ascetic fire, visionary and transformative."},
    {"id": 26, "name": "Uttara Bhadrapada", "sanskrit": "उत्तरभाद्रपदा", "deity": "Ahirbudhnya", "symbol": "Back of Funeral Cot", "ruler": "Saturn", "range": "Pisces 3°20′–16°40′", "gana": "Manushya", "quality": "Deep, compassionate, wise", "description": "The latter blessed foot. Serpent of the depths — wise, compassionate, and mystically profound."},
    {"id": 27, "name": "Revati", "sanskrit": "रेवती", "deity": "Pushan", "symbol": "Fish / Drum", "ruler": "Mercury", "range": "Pisces 16°40′–30°", "gana": "Deva", "quality": "Nurturing, journeying, final", "description": "The wealthy. Revati guides souls safely home — gentle, nurturing, the last star of the zodiac."},
]


def get_graha(gid: str):
    return next((g for g in GRAHAS if g["id"] == gid), None)


def get_nakshatra(nid: int):
    return next((n for n in NAKSHATRAS if n["id"] == nid), None)
